### ISSUE TITLE
Remove cache

### ISSUE THREAD

**Issue by MichaelCurrin** [Jwmc999/Jwmc999.github.io#8]
Add to `.gitignore`
```
.jekyll-cache
```

And delete the directory in version control.

Here is what I use for Jekyll 4 ignore file

```
.jekyll-cache/
.jekyll-metadata

.bundle/
vendor/

node_modules/
assets/

_site/
```

https://github.com/MichaelCurrin/my-github-projects/blob/master/.gitignore

**Comment by Jwmc999** [comment]
Thank you very very much! I added cache to the `.gitnore`. Also added others to `.gitnore`
